---
name: General
about: If you find any issues with the program, which seem to hamper the experience,
  please mention it in this page.
title: ''
labels: ''
assignees: ''

---

> **_Anomalous Behavior:_**  Describe in detail, the problem that you are facing.
       
=>

> **_Expected Behavior:_**  Describe in detail, how you want the program to actually function.

=>

> **_Suggestions to solve the issue:_** Any advice, to get the required changes.

=>
