name: "📋 General Issues"
description: "If you find any issue in the program, which seems to hamper with the existing code, report it here"
title: "📋General Issues:"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank You for helping us make the program better!🙏
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "👎 Actual Behavior"
      description: "What actually happened? Add screenshots, if applicable."
      placeholder: "It actually ..." 
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "👍 Expected behavior"
      description: "How did you expect the program to behave?"
      placeholder: "It should ..."
  - type: textarea
    id: Suggestions-to-rectify
    validations:
      required: true
    attributes:
      label: "✍️ Suggestions to rectify this issue"
      description: "If you have any ideas that can help us rectify the issue, please mention them:"
      placeholder: "...."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you spent some time to check if this issue has been raised before?"
      description: "Have you Googled for a similar issue or checked our older issues for a similar bug?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true